### ISSUE TITLE
Messages with even number of characters not read properly in RFC 6455 version

### ISSUE THREAD

**Issue by armandoheor** [mirek/CoreWebSocket#1]
From what I've been testing it looks like a message with an even number of characters is not read properly.

I identified that the payload data for messages with even number of characters is not masked while the ones with odd number of characters are. I don't know if that makes a difference.

**Comment by mirek** [comment]
good catch, can't really test it properly now, can you have a look if this fixes it? https://github.com/mirek/CoreWebSocket/commit/300dcba1da13645da0bd0174965be9a1f130ec1b

**Comment by armandoheor** [comment]
I ran a few tests and it looks like it is fixed. Nice job! Thanks.
