### ISSUE TITLE
CoreWebSocket Vs. SocketRocket

### ISSUE THREAD

**Issue by ma11hew28** [mirek/CoreWebSocket#5]
In the `README.md` explain the pros & cons of using CoreWebSocket as compared to other libraries, such as SocketRocket.

**Comment by mirek** [comment]
Matt, this is question for SO.

**Comment by ma11hew28** [comment]
Actually, SO doesn't allow these types of questions. I guess they're too opinionated.

**Comment by mirek** [comment]
Why don't you try both and pick the one you like then.
